### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by tstir** [mikenguyen13/causalverse#1]
Hi

I'm using R version: 4.4.1 on mac and when trying to install causalverse the following error is shown:

ERROR: dependencies ‘rdbounds’, ‘MedBounds’ are not available for package ‘causalverse’
removing ‘/Library/Frameworks/R.framework/Versions/4.4-arm64/Resources/library/causalverse’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/6q/jcxx3w7d2sdb31jdp7y4qc_h0000gn/T//RtmpibK5PA/file5fb1ac7c2e8/causalverse_0.0.0.9000.tar.gz’ had non-zero exit status

**Comment by mikenguyen13** [comment]
Hi, 
You have to install rdbounds and MedBounds package before installing causalverse

**Comment by tstir** [comment]
Thanks for making me aware, it appeared to be skipping installing them automatically so I installed manually. Thanks.
